name: Deploy

on:
  push:
    branches:
      - v2

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      # - name: Caching Build Dependancies
      #   id: site-cache-build
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       dist
      #       .cache
      #       node_modules
      #     key: ${{ runner.os }}-whitfordworkshop-site-build-${{ github.run_id }}
      #     restore-keys: |
      #       ${{ runner.os }}-whitfordworkshop-site-build-
      - name: Install Dependancies
        run: npm install
      - name: Build Stage
        run: npm run build
      - name: Setup AWS Access
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-southeast-2
      - name: Deploy to S3
        run: aws s3 sync ./build/. s3://sydneymusic.net-prod/ --delete --exclude .gitkeep
